name: API Request Workflow

on:
  workflow_call:
    inputs:
      json_string:
        required: true
        type: string

jobs:
  send-api-request:
    runs-on: ubuntu-latest
    env:
      REQUESTS_JSON: ${{ inputs.json_string }}

    container:
      image: python:3.10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install requests package
      run: pip install requests

    - name: Send API request and save response
      run: python send_api_request.py

    - name: Commit and push response
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add response.json
        git commit -m 'Dataset Created Please check JSON file to confirm'
        git push
