name: API Request Workflow

on:
  workflow_call:
    inputs:
      json_string:
        required: true
        type: string

jobs:
  send-api-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install requests package
      run: pip install requests

    - name: Send API request and save response
      env:
        REQUESTS_JSON: ${{ inputs.json_string }}
      run: python send_api_request.py

    - name: Commit and push response
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add response.json
        git commit -m 'Add API response'
        git push
